# Generated by Django 5.0.6 on 2024-07-24 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_curatoremployees_options_and_more'),
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectassignment',
            options={'verbose_name': 'Назначение сотрудника на проект'},
        ),
        migrations.AlterField(
            model_name='projectassignment',
            name='employee',
            field=models.ForeignKey(limit_choices_to={'role': 'employee'}, on_delete=django.db.models.deletion.CASCADE, related_name='project_assignments', to='employees.employee', verbose_name='Сотрудник'),
        ),
        migrations.AlterUniqueTogether(
            name='projectassignment',
            unique_together={('employee', 'project')},
        ),
    ]
