# Generated by Django 5.0.6 on 2024-07-29 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_projectassignment_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.AddField(
            model_name='project',
            name='date_end',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания проекта'),
        ),
        migrations.AddField(
            model_name='project',
            name='date_start',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала проекта'),
        ),
        migrations.AddField(
            model_name='project',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Удален'),
        ),
    ]
