# Generated by Django 5.0.6 on 2024-07-31 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_project_description_project_date_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время удаления'),
        ),
    ]
