# Generated by Django 5.0.6 on 2024-08-15 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectassignment',
            name='date_of_employment',
            field=models.DateField(blank=True, null=True, verbose_name='Дата первого рабочего дня на проекте'),
        ),
    ]
