# Generated by Django 5.0.6 on 2024-08-15 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_alter_employee_telegram_nickname'),
        ('projects', '0006_projectassignment_date_of_employment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectassignment',
            options={'verbose_name': 'Назначение сотрудника на проект', 'verbose_name_plural': 'Назначения сотрудников на проекты'},
        ),
        migrations.AlterField(
            model_name='projectassignment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_assignments', to='employees.employee', verbose_name='Сотрудник'),
        ),
    ]
