# Generated by Django 5.0.6 on 2024-08-16 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_remove_employee_projects_and_more'),
        ('projects', '0007_alter_projectassignment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectassignment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects_assigned', to='employees.employee', verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='projectassignment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees_assigned', to='projects.project', verbose_name='Проект'),
        ),
    ]
