# Generated by Django 5.0.6 on 2024-08-26 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_projectassignment_employee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='employees',
        ),
    ]
