# Generated by Django 5.0.6 on 2024-07-30 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0005_employee_date_of_dismission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.CharField(verbose_name='Время начала')),
                ('date', models.DateField(verbose_name='Дата')),
                ('booked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.employee', verbose_name='Забронирован сотрудником')),
            ],
            options={
                'unique_together': {('start_time', 'date')},
            },
        ),
    ]
