# Generated by Django 5.0.6 on 2024-07-23 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_initial'),
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='pollstatus',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employee', verbose_name='Сотрудник'),
        ),
        migrations.AddField(
            model_name='pollstatus',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.pollquestion', verbose_name='Опрос'),
        ),
        migrations.AddField(
            model_name='pollstatus',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='question',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='questions.pollquestion'),
        ),
        migrations.AddField(
            model_name='questioncondition',
            name='previous_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previous_conditions', to='questions.question'),
        ),
        migrations.AddField(
            model_name='questioncondition',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='questions.question'),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='answered_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employee', verbose_name='Сотрудник'),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question', verbose_name='Вопрос'),
        ),
        migrations.AlterUniqueTogether(
            name='pollstatus',
            unique_together={('employee', 'poll')},
        ),
    ]
