# Generated by Django 5.0.6 on 2024-07-23 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_telegram_user_id_and_more'),
        ('questions', '0003_alter_pollstatus_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pollstatus',
            unique_together={('employee', 'poll', 'target_employee')},
        ),
    ]
