# Generated by Django 5.0.6 on 2024-07-30 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_alter_pollstatus_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollquestion',
            name='poll_type',
            field=models.CharField(choices=[('onboarding', 'Онбординг'), ('offboarding', 'Офбординг'), ('event', 'Опрос о мероприятии'), ('project', 'Опрос о проекте')], default='onboarding', max_length=50, verbose_name='Тип опроса'),
        ),
    ]
