# Generated by Django 5.0.6 on 2024-07-30 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_pollquestion_poll_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyboardtype',
            name='question_type',
            field=models.CharField(choices=[('yes_no', 'Yes/No'), ('finish', 'Finish'), ('message', 'Message'), ('next', 'Next'), ('numbers', 'Numbers'), ('slots', 'Slots')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('yes_no', 'Yes/No'), ('finish', 'Finish'), ('message', 'Message'), ('next', 'Next'), ('numbers', 'Numbers'), ('slots', 'Slots')], max_length=50),
        ),
    ]
