# Generated by Django 5.0.6 on 2024-08-01 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('questions', '0006_alter_keyboardtype_question_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollquestion',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pollquestion',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pollquestion',
            name='poll_type',
            field=models.CharField(choices=[('onboarding', 'Онбординг'), ('offboarding', 'Офбординг')], default='onboarding', max_length=50, verbose_name='Тип опроса'),
        ),
        migrations.AlterField(
            model_name='questioncondition',
            name='answer_condition',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('some_text', 'some_text'), ('next', 'Next'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=255),
        ),
    ]
