# Generated by Django 5.0.6 on 2024-08-01 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_pollquestion_content_type_pollquestion_object_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
