# Generated by Django 5.0.6 on 2024-08-06 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_question_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackuser',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время удаления'),
        ),
        migrations.AddField(
            model_name='feedbackuser',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Удален'),
        ),
        migrations.AddField(
            model_name='pollquestion',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время удаления'),
        ),
        migrations.AddField(
            model_name='pollquestion',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Удален'),
        ),
        migrations.AlterUniqueTogether(
            name='questioncondition',
            unique_together={('question', 'previous_question', 'answer_condition')},
        ),
    ]
