# Generated by Django 5.0.6 on 2024-08-12 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_feedbackuser_deleted_at_feedbackuser_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollquestion',
            name='poll_number',
            field=models.PositiveIntegerField(default=1, verbose_name='Порядковый номер опроса'),
        ),
    ]
