# Generated by Django 5.0.6 on 2024-08-13 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_alter_employee_telegram_nickname'),
        ('questions', '0011_alter_pollquestion_intended_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='target_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_employee_useranswer', to='employees.employee', verbose_name='Сотрудник, по которому был дан ответ'),
        ),
    ]
