# Generated by Django 5.0.6 on 2024-08-14 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0012_alter_useranswer_target_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeedbackUser',
        ),
    ]
