# Generated by Django 5.0.6 on 2024-08-15 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('questions', '0013_delete_feedbackuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollquestion',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='pollquestion',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
