# Generated by Django 5.0.6 on 2024-08-19 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0016_alter_pollstatus_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questioncondition',
            name='answer_condition',
            field=models.CharField(choices=[('yes', 'Да'), ('no', 'Нет'), ('some_text', 'Некоторый текст'), ('next', 'Следующий'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=255),
        ),
    ]
