# Generated by Django 5.0.6 on 2024-08-21 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0017_alter_questioncondition_answer_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='requires_attention',
            field=models.BooleanField(default=False, verbose_name='Требует внимания'),
        ),
    ]
