# Generated by Django 5.0.6 on 2024-08-22 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0019_pollstatus_deleted_at_pollstatus_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pollstatus',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='pollstatus',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='pollstatus',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='В архиве'),
        ),
    ]
