# Generated by Django 5.0.6 on 2024-08-29 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0020_remove_pollstatus_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keyboardtype',
            options={'verbose_name': 'Клавиатура', 'verbose_name_plural': 'Клавиатуры'},
        ),
        migrations.AlterModelOptions(
            name='pollquestion',
            options={'verbose_name': 'Опрос', 'verbose_name_plural': 'Опросы'},
        ),
        migrations.AlterModelOptions(
            name='pollstatus',
            options={'verbose_name': 'Запланированный опрос', 'verbose_name_plural': 'Запланированные опросы'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['id'], 'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='questioncondition',
            options={'verbose_name': 'Условие вопроса', 'verbose_name_plural': 'Условия вопросов'},
        ),
        migrations.AlterModelOptions(
            name='useranswer',
            options={'verbose_name': 'Ответ', 'verbose_name_plural': 'Ответы'},
        ),
    ]
