# Generated by Django 5.0.6 on 2024-09-09 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0021_alter_keyboardtype_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollstatus',
            name='created_by_admin',
            field=models.BooleanField(default=False, verbose_name='Создано администратором'),
        ),
    ]
