# Generated by Django 5.0.6 on 2024-09-11 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0018_employee_risk_status_alter_employee_status'),
        ('questions', '0022_pollstatus_created_by_admin'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='useranswer',
            unique_together={('employee', 'target_employee', 'question')},
        ),
    ]
