# Generated by Django 5.0.6 on 2024-09-11 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0023_alter_useranswer_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category_analytics',
            field=models.CharField(blank=True, choices=[('general_health', 'Общее самочувствие'), ('responsibilities', 'Понимание обязанностей и функционала'), ('job_expectations', 'Ожидания от работы'), ('team_satisfactions', 'Удовлетворенность командой'), ('onboarding_satisfactions', 'Удовлетворенность онбордингом'), ('interest_project', 'Заинтересованность проектом'), ('quality_feedback', 'Качество обратной связи'), ('project_expectations', 'Ожидания от проекта'), ('discipline', 'Дисциплина'), ('quality_tasks', 'Качество задач'), ('quality_interactions', 'Качество взаимодействия'), ('involvement', 'Вовлеченность'), ('answer_speed', 'Скорость ответа'), ('presence_meeting', 'Присутствие на встречах')], default=None, max_length=30, null=True, verbose_name='Категория аналитики'),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='category_analytics',
            field=models.CharField(blank=True, choices=[('general_health', 'Общее самочувствие'), ('responsibilities', 'Понимание обязанностей и функционала'), ('job_expectations', 'Ожидания от работы'), ('team_satisfactions', 'Удовлетворенность командой'), ('onboarding_satisfactions', 'Удовлетворенность онбордингом'), ('interest_project', 'Заинтересованность проектом'), ('quality_feedback', 'Качество обратной связи'), ('project_expectations', 'Ожидания от проекта'), ('discipline', 'Дисциплина'), ('quality_tasks', 'Качество задач'), ('quality_interactions', 'Качество взаимодействия'), ('involvement', 'Вовлеченность'), ('answer_speed', 'Скорость ответа'), ('presence_meeting', 'Присутствие на встречах')], default=None, max_length=30, null=True, verbose_name='Категория аналитики'),
        ),
    ]
