# Generated by Django 5.0.6 on 2024-09-13 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0025_alter_question_category_analytics_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswer',
            name='category_analytics',
        ),
    ]
