# Generated by Django 5.0.6 on 2024-09-16 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0026_remove_useranswer_category_analytics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollquestion',
            name='poll_type',
            field=models.CharField(choices=[('onboarding', 'Онбординг'), ('offboarding', 'Офбординг'), ('feedback', 'Обратная связь'), ('intermediate_feedback', 'Промежуточная обратная связь')], default='onboarding', max_length=50, verbose_name='Тип опроса'),
        ),
    ]
