# Generated by Django 5.0.6 on 2024-09-24 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0027_alter_pollquestion_poll_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pollquestion',
            options={'verbose_name': 'Шаблон опроса', 'verbose_name_plural': 'Шаблоны опросов'},
        ),
        migrations.AlterModelOptions(
            name='pollstatus',
            options={'verbose_name': 'Статус опроса', 'verbose_name_plural': 'Статусы опросов'},
        ),
    ]
