# Generated by Django 5.0.6 on 2024-07-23 11:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CuratorEmployees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удален')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('role', models.CharField(choices=[('admin', 'Администратор'), ('hr', 'HR'), ('curator', 'Куратор'), ('employee', 'Сотрудник')], default='employee', max_length=20, verbose_name='Роль сотрудника')),
                ('full_name', models.CharField(default='ФИО', max_length=255, verbose_name='ФИО')),
                ('telegram_nickname', models.CharField(default='тг-никнейм', max_length=100, verbose_name='Ник в Telegram')),
                ('date_of_employment', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата первого рабочего дня')),
                ('is_archived', models.BooleanField(default=False, verbose_name='В архиве')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
