# Generated by Django 5.0.6 on 2024-07-23 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='telegram_user_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Telegram ID пользователя'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_employment',
            field=models.DateField(blank=True, null=True, verbose_name='Дата первого рабочего дня'),
        ),
    ]
