# Generated by Django 5.0.6 on 2024-07-24 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_telegram_user_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curatoremployees',
            options={'verbose_name': 'Куратор сотрудника'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterField(
            model_name='curatoremployees',
            name='curator',
            field=models.ForeignKey(limit_choices_to={'role': 'curator'}, on_delete=django.db.models.deletion.CASCADE, related_name='curated_employees', to='employees.employee', verbose_name='Куратор'),
        ),
        migrations.AlterField(
            model_name='curatoremployees',
            name='employee',
            field=models.ForeignKey(limit_choices_to={'role': 'employee'}, on_delete=django.db.models.deletion.CASCADE, related_name='curators', to='employees.employee', verbose_name='Сотрудник'),
        ),
    ]
