# Generated by Django 5.0.6 on 2024-07-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_curatoremployees_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='date_of_dismission',
            field=models.DateField(blank=True, null=True, verbose_name='Дата увольнения'),
        ),
    ]
