# Generated by Django 5.0.6 on 2024-07-30 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_employee_date_of_dismission'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='description',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='О сотруднике'),
        ),
    ]
