# Generated by Django 5.0.6 on 2024-07-31 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_employee_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время удаления'),
        ),
    ]
