# Generated by Django 5.0.6 on 2024-08-02 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_alter_employee_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='telegram_nickname',
            field=models.CharField(default='тг-никнейм', max_length=100, unique=True, verbose_name='Ник в Telegram'),
        ),
    ]
