# Generated by Django 5.0.6 on 2024-08-05 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_alter_employee_telegram_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='telegram_nickname',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Ник в Telegram'),
        ),
    ]
