# Generated by Django 5.0.6 on 2024-08-05 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_alter_employee_telegram_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='telegram_user_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Telegram ID пользователя'),
        ),
    ]
