# Generated by Django 5.0.6 on 2024-08-09 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_alter_employee_telegram_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='telegram_nickname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ник в Telegram'),
        ),
    ]
