# Generated by Django 5.0.6 on 2024-08-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_remove_employee_projects_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='date_meeting',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Встреча по итогам ИС'),
        ),
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('onboarding', 'Онбординг'), ('offboarding', 'Оффбординг'), ('adapted', 'Адаптированный'), ('fired', 'Уволен'), ('riskzone', 'В зоне риска'), ('observable', 'Наблюдаемый')], default='onboarding', max_length=20, verbose_name='Роль сотрудника'),
        ),
    ]
