# Generated by Django 5.0.6 on 2024-08-28 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0014_alter_employee_status'),
        ('questions', '0020_remove_pollstatus_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='onboarding_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_onboarding_status', to='questions.pollstatus', verbose_name='Статус опроса сотрудника'),
        ),
    ]
