# Generated by Django 5.0.6 on 2024-08-29 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0015_employee_onboarding_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curatoremployees',
            options={'verbose_name': 'Куратор сотрудника', 'verbose_name_plural': 'Кураторы сотрудников'},
        ),
    ]
