# Generated by Django 5.0.6 on 2024-09-05 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0017_employee_is_curator_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='risk_status',
            field=models.CharField(choices=[('riskzone', 'В зоне риска'), ('observable', 'Наблюдаемый'), ('noproblem', 'Без проблем')], default='noproblem', max_length=20, verbose_name='Статус риска'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('onboarding', 'Онбординг'), ('offboarding', 'Оффбординг'), ('adapted', 'Адаптированный'), ('fired', 'Уволен')], default='onboarding', max_length=20, verbose_name='Статус сотрудника'),
        ),
    ]
