# Generated by Django 5.0.6 on 2024-09-18 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0018_employee_risk_status_alter_employee_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('onboarding', 'Испытательный срок'), ('offboarding', 'Оффбординг'), ('adapted', 'Адаптированный'), ('fired', 'Уволен')], default='onboarding', max_length=20, verbose_name='Статус сотрудника'),
        ),
    ]
