# Generated by Django 5.0.6 on 2024-08-09 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_initial'),
        ('employees', '0011_alter_employee_telegram_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_comments', to='employees.employee', verbose_name='Автор'),
        ),
    ]
