# Generated by Django 5.0.6 on 2024-09-18 23:24

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_managers_remove_customuser_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=128, unique=True, verbose_name='Email'),
        ),
    ]
