# Generated by Django 5.0.6 on 2024-09-23 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_authenticationapplication_authenticationtoken_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authenticationtoken',
            old_name='profile',
            new_name='user',
        ),
    ]
