# Generated by Django 5.0.6 on 2024-09-27 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_profile_authenticationtoken_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authenticationtoken',
            old_name='user',
            new_name='profile',
        ),
    ]
