# Generated by Django 5.0.6 on 2024-08-14 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_alter_employee_telegram_nickname'),
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedbackuser',
            options={'verbose_name': 'Фидбек', 'verbose_name_plural': 'Фидбеки'},
        ),
        migrations.AlterField(
            model_name='feedbackuser',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee', verbose_name='Сотрудник (Автор фидбека)'),
        ),
    ]
